name: fifty
description: daily obtainable fitness goals

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  fl_chart: ^0.51.0
  url_launcher: ^6.1.2
  path_provider: ^2.0.10
  package_info_plus: ^1.4.2
  flutter_local_notifications: ^9.6.1
  auto_size_text: ^3.0.0
  uuid: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
